FROM confluentinc/cp-kafka-connect:7.5.1

    # Set environment variables for Kafka Connect configuration
ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components" \
    # Directories where Kafka Connect will look for plugins
    CONNECT_BOOTSTRAP_SERVERS="broker1:29092,broker2:29092,broker3:29092" \
    # Kafka broker(s) that Kafka Connect should connect to
    CONNECT_REST_PORT=8084 \
    # Port where Kafka Connect's REST API will listen
    CONNECT_GROUP_ID=kafka-connect \
    # Group ID for the Kafka Connect cluster
    CONNECT_CONFIG_STORAGE_TOPIC=_connect-configs \
    # Topic for storing connector configuration data
    CONNECT_OFFSET_STORAGE_TOPIC=_connect-offsets \
    # Topic for storing connector offsets
    CONNECT_STATUS_STORAGE_TOPIC=_connect-status \
    # Topic for storing connector status
    CONNECT_KEY_CONVERTER=org.apache.kafka.connect.storage.StringConverter \
    # Class used to convert keys from Kafka Connect format to Kafka format
    CONNECT_VALUE_CONVERTER=io.confluent.connect.avro.AvroConverter \
    # Class used to convert values from Kafka Connect format to Kafka format
    CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL='http://schema-registry:8081' \
    # URL of the Schema Registry service
    CONNECT_REST_ADVERTISED_HOST_NAME=kafka-connect \
    # Hostname advertised to other Kafka Connect instances
    CONNECT_LOG4J_APPENDER_STDOUT_LAYOUT_CONVERSIONPATTERN="[%d] %p %X{connector.context}%m (%c:%L)%n" \
    # Pattern used for log messages
    CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR="1" \
    # Replication factor for the configuration topic
    CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR="1" \
    # Replication factor for the offset topic
    CONNECT_STATUS_STORAGE_REPLICATION_FACTOR="1" 
    # Replication factor for the status topic

    # Copy the Kafka Connect plugins from your local connect-plugins directory 
    # into the /usr/share/confluent-hub-components/ directory in the image
COPY ./connect-plugins/ /usr/share/confluent-hub-components/